# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.19.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.19.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arthur/Desktop/CHUPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arthur/Desktop/CHUPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.19.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.19.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arthur/Desktop/CHUPS/CMakeFiles /Users/arthur/Desktop/CHUPS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arthur/Desktop/CHUPS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHUPS

# Build rule for target.
CHUPS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CHUPS
.PHONY : CHUPS

# fast build rule for target.
CHUPS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/build
.PHONY : CHUPS/fast

src/common.o: src/common.c.o

.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/common.c.s
.PHONY : src/common.c.s

src/file.o: src/file.c.o

.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i

.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s

.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/file.c.s
.PHONY : src/file.c.s

src/host.o: src/host.c.o

.PHONY : src/host.o

# target to build an object file
src/host.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/host.c.o
.PHONY : src/host.c.o

src/host.i: src/host.c.i

.PHONY : src/host.i

# target to preprocess a source file
src/host.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/host.c.i
.PHONY : src/host.c.i

src/host.s: src/host.c.s

.PHONY : src/host.s

# target to generate assembly for a file
src/host.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/host.c.s
.PHONY : src/host.c.s

src/logs.o: src/logs.c.o

.PHONY : src/logs.o

# target to build an object file
src/logs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/logs.c.o
.PHONY : src/logs.c.o

src/logs.i: src/logs.c.i

.PHONY : src/logs.i

# target to preprocess a source file
src/logs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/logs.c.i
.PHONY : src/logs.c.i

src/logs.s: src/logs.c.s

.PHONY : src/logs.s

# target to generate assembly for a file
src/logs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/logs.c.s
.PHONY : src/logs.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/main.c.s
.PHONY : src/main.c.s

src/menu.o: src/menu.c.o

.PHONY : src/menu.o

# target to build an object file
src/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/menu.c.o
.PHONY : src/menu.c.o

src/menu.i: src/menu.c.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/menu.c.i
.PHONY : src/menu.c.i

src/menu.s: src/menu.c.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/menu.c.s
.PHONY : src/menu.c.s

src/synack.o: src/synack.c.o

.PHONY : src/synack.o

# target to build an object file
src/synack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/synack.c.o
.PHONY : src/synack.c.o

src/synack.i: src/synack.c.i

.PHONY : src/synack.i

# target to preprocess a source file
src/synack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/synack.c.i
.PHONY : src/synack.c.i

src/synack.s: src/synack.c.s

.PHONY : src/synack.s

# target to generate assembly for a file
src/synack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/synack.c.s
.PHONY : src/synack.c.s

src/textcolor.o: src/textcolor.c.o

.PHONY : src/textcolor.o

# target to build an object file
src/textcolor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/textcolor.c.o
.PHONY : src/textcolor.c.o

src/textcolor.i: src/textcolor.c.i

.PHONY : src/textcolor.i

# target to preprocess a source file
src/textcolor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/textcolor.c.i
.PHONY : src/textcolor.c.i

src/textcolor.s: src/textcolor.c.s

.PHONY : src/textcolor.s

# target to generate assembly for a file
src/textcolor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHUPS.dir/build.make CMakeFiles/CHUPS.dir/src/textcolor.c.s
.PHONY : src/textcolor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CHUPS"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/host.o"
	@echo "... src/host.i"
	@echo "... src/host.s"
	@echo "... src/logs.o"
	@echo "... src/logs.i"
	@echo "... src/logs.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/synack.o"
	@echo "... src/synack.i"
	@echo "... src/synack.s"
	@echo "... src/textcolor.o"
	@echo "... src/textcolor.i"
	@echo "... src/textcolor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

